# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: detect-private-key
  - repo: https://github.com/ambv/black
    rev: 22.10.0
    hooks:
      - id: black
        verbose: true
        additional_dependencies: [toml]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        verbose: true
        args:
          [
            --exclude,
            ".venv,app/migrations/versions/",
            --max-line-length,
            "127",
            --count,
            --exit-zero,
            --max-complexity,
            "10",
            --show-source,
            --statistics,
          ]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        verbose: true
        additional_dependencies: [toml]
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v6.14.1
    hooks:
      - id: cspell
        args: [--config, "./cSpell.json", "**/*.py"]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args:
          [
            -x,
            "./app/.venv,**/tests/**,**/node_modules/**",
            -r,
            "./app",
            "**/*.py",
          ]
